import { spawnCommand, type SpawnCommand } from "../cli/system-actions";
import { resolveHostPlatform } from "../cli/platform";

export const FEEDBACK_EMAIL = "miguel.garglez@gmail.com";
export const GITHUB_ISSUES_URL = "https://github.com/miguelgarglez/video-digest/issues";

export type FeedbackOrigin = "failed-workflow" | "main-menu";

export type SupportContext = Readonly<{
  appVersion: string;
  architecture: string;
  osName: string;
  osVersion: string;
}>;

export type FeedbackLinks = Readonly<{
  email: string;
  githubIssue: string;
}>;

type ContextInput = Readonly<{
  appVersion: string;
  architecture: string;
  platform?: NodeJS.Platform;
  readText?: (path: string) => Promise<string>;
  run?: SpawnCommand;
}>;

export async function resolveSupportContext(input: ContextInput): Promise<SupportContext> {
  const platform = resolveHostPlatform(input.platform ?? process.platform);
  const osName = platform === "darwin" ? "macOS" : "Linux";
  let osVersion = "unknown";

  try {
    if (platform === "darwin") {
      const result = await (input.run ?? spawnCommand)(["/usr/bin/sw_vers", "-productVersion"]);
      const candidate = result.stdout.trim();
      if (result.exitCode === 0 && /^\d+(?:\.\d+){1,2}$/.test(candidate)) osVersion = candidate;
    } else {
      const source = await (input.readText ?? defaultReadText)("/etc/os-release");
      osVersion = parseOsRelease(source) ?? "unknown";
    }
  } catch {
    // Support context is optional and must never block TUI startup.
  }

  return {
    appVersion: safeFact(input.appVersion),
    architecture: safeFact(input.architecture),
    osName,
    osVersion: safeFact(osVersion),
  };
}

export function buildFeedbackLinks(context: SupportContext, origin: FeedbackOrigin): FeedbackLinks {
  const body = feedbackBody(context, origin);
  const email = `mailto:${FEEDBACK_EMAIL}?subject=${encodeURIComponent("Video Digest feedback")}` +
    `&body=${encodeURIComponent(body)}`;

  const githubIssue = new URL(`${GITHUB_ISSUES_URL}/new`);
  githubIssue.searchParams.set("title", "[Bug] ");
  githubIssue.searchParams.set("body", body);

  return { email, githubIssue: githubIssue.toString() };
}

function feedbackBody(context: SupportContext, origin: FeedbackOrigin): string {
  return [
    "What were you trying to do?",
    "",
    "What did you expect?",
    "",
    "What happened?",
    "",
    "Technical context (generated by Video Digest):",
    `- Video Digest: ${safeFact(context.appVersion)}`,
    `- OS: ${safeFact(context.osName)} ${safeFact(context.osVersion)}`,
    `- Architecture: ${safeFact(context.architecture)}`,
    `- Opened from: ${origin === "failed-workflow" ? "Failed workflow" : "Main menu"}`,
    "",
    "Do not include API keys, private artifacts, or sensitive paths.",
  ].join("\n");
}

function parseOsRelease(contents: string): string | null {
  const pretty = contents.match(/^PRETTY_NAME=(?:"([^"]+)"|(\S+))/m);
  const candidate = pretty?.[1] ?? pretty?.[2];
  if (candidate && candidate.length <= 80 && !/[\r\n]/.test(candidate)) return candidate;
  return null;
}

async function defaultReadText(path: string): Promise<string> {
  return await Bun.file(path).text();
}

function safeFact(value: string): string {
  const candidate = value.trim();
  return candidate.length > 0 && candidate.length <= 80 && !/[\r\n]/.test(candidate)
    ? candidate
    : "unknown";
}
